#!/usr/bin/env ruby
#^syntax detection
# See https://github.com/bodepd/librarian-puppet-simple for additional docs
#
# Important information for fuel-library:
# With librarian-puppet-simple you *must* remove the existing folder from the
# repo prior to trying to run librarian-puppet as it will not remove the folder
# for you and you may run into some errors.
#
############
# Examples #
############
# From git repo
#  mod 'stdlib',
#    :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git',
#    :ref => '4.6.x'
#
# From tarbal
#  mod 'stdlib',
#    :tarbal => 'https://forgeapi.puppetlabs.com/v3/files/puppetlabs-stdlib-4.6.0.tar.gz'
#
#

# Pull in puppet-aodh
mod 'aodh',
    :git => 'http://git.fx-dev.com/fuel-infra/puppet-aodh ',
    :ref => 'origin/stable/mitaka'

# Pull in puppet-ceilometer
mod 'ceilometer',
    :git => 'http://git.fx-dev.com/fuel-infra/puppet-ceilometer ',
    :ref => 'origin/stable/mitaka'

# Pull in openstack-cinder
mod 'cinder',
    :git => 'http://git.fx-dev.com/fuel-infra/openstack-cinder ',
    :ref => 'origin/stable/mitaka'

# Pull in puppet-glance
mod 'glance',
    :git => 'http://git.fx-dev.com/fuel-infra/puppet-glance ',
    :ref => '8.2.0'

# Pull in puppet-heat
mod 'heat',
    :git => 'http://git.fx-dev.com/fuel-infra/puppet-heat ',
    :ref => 'origin/stable/mitaka'

# Pull in puppet-horizon
mod 'horizon',
    :git => 'http://git.fx-dev.com/fuel-infra/puppet-horizon ',
    :ref => '8.2.0'

# Pull in puppet-ironic
mod 'ironic',
    :git => 'http://git.fx-dev.com/fuel-infra/puppet-ironic ',
    :ref => 'origin/stable/mitaka'

# Pull in puppet-keystone
mod 'keystone',
    :git => 'http://git.fx-dev.com/fuel-infra/puppet-keystone ',
    :ref => 'origin/stable/mitaka'

# Pull in puppet-openstacklib
mod 'openstacklib',
    :git => 'http://git.fx-dev.com/fuel-infra/puppet-openstacklib ',
    :ref => '8.2.0'

# Pull in puppet-neutron
mod 'neutron',
    :git => 'http://git.fx-dev.com/fuel-infra/puppet-neutron ',
    :ref => 'origin/stable/mitaka'

# Pull in puppet-nova
mod 'nova',
    :git => 'http://git.fx-dev.com/fuel-infra/puppet-nova ',
    :ref => 'origin/stable/mitaka'

# Pull in puppet-murano
mod 'murano',
    :git => 'http://git.fx-dev.com/fuel-infra/puppet-murano ',
    :ref => 'origin/stable/mitaka'

# Pull in puppet-sahara
mod 'sahara',
    :git => 'http://git.fx-dev.com/fuel-infra/puppet-sahara ',
    :ref => 'origin/stable/mitaka'

# Pull in puppet-swift
mod 'swift',
    :git => 'http://git.fx-dev.com/fuel-infra/puppet-swift ',
    :ref => '8.2.0'
